#!/usr/bin/python3

import sys
import math


def factorize(n):
    """
    Factorize a number into two smaller numbers.

    Parameters:
    n (int): The number to be factorized.

    Returns:
    tuple: A tuple containing two factors of n.
    """
    for i in range(2, int(math.sqrt(n)) + 1):
        if n % i == 0:
            return n // i, i  # Return the larger factor first
    return n, 1  # In case no factors are found


def main(filename):
    """
    Read numbers from a file and factorize each number.

    Parameters:
    filename (str): The name of the file containing numbers to be factorized.
    """
    with open(filename, 'r') as file:
        numbers = file.readlines()

    for number in numbers:
        n = int(number.strip())
        p, q = factorize(n)
        print(f"{n}={p}*{q}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    filename = sys.argv[1]
    main(filename)
